---
title: "New figures AgCLIM50"
author: "Michiel van Dijk"
date: "31 October 2017"
output: word_document
---


```{r setup, include=FALSE}
library(pacman)
p_load(rprojroot, tidyverse)
root <- find_root(is_rstudio_project)

p_load(knitr)
knitr::opts_chunk$set(
  fig.width=8, fig.height=6,
  dpi = 300,
  echo=FALSE, warning=FALSE, message=FALSE,
  fig.path = file.path(root,"Fig_tab_map/out-"))

p_load(pander)
panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)
panderOptions('digits', 2)
panderOptions('round', 2)

source(file.path(root, "code/plots_for_ERL.R"))
```


# AGR_PROD
```{r AGR_PROD}
barplot2_f(TOTAL_WLD, "PROD", "AGR", ypos = 1.8, 1, 2)
barplot3_f(TOTAL_WLD, "PROD", "AGR", ypos = 75, 0, 80)
barplot4_f(TOTAL_WLD_mean, "PROD", "AGR")
barplot5_f(scen_diff, "PROD", "AGR")
barplot6_f(scen_diff, "PROD", "AGR") # Fig 2 in ERL
barplot6_f(scen_diff_upd, "PROD", "AGR")
```

# CRP_AREA
NB: does not include lvst area!
```{r CRP_AREA}
barplot2_f(TOTAL_WLD, "AREA", "CRP", ypos = 1.45, 0.5, 1.5)
barplot3_f(TOTAL_WLD, "AREA", "CRP", ypos = 40, -15, 45)
barplot4_f(TOTAL_WLD_mean, "AREA", "CRP")
barplot5_f(scen_diff, "AREA", "CRP")
barplot6_f(scen_diff, "AREA", "CRP") # Fig 3a in ERL
barplot6_f(scen_diff_upd, "AREA", "CRP")

```


# LSP_AREA
NB: does not include lvst area!
```{r LSP_AREA}
barplot2_f(TOTAL_WLD, "AREA", "LSP", ypos = 1.45, 0.5, 1.5)
barplot3_f(TOTAL_WLD, "AREA", "LSP", ypos = 20, -25, 25)
barplot4_f(TOTAL_WLD_mean, "AREA", "LSP")
barplot5_f(scen_diff, "AREA", "LSP")
barplot6_f(scen_diff, "AREA", "LSP") # Fig 3b in ERL
barplot6_f(scen_diff_upd, "AREA", "LSP")
```


# XPRP_AGR
```{r XPRP_AGR}
barplot2_f(TOTAL_WLD, "XPRP", "AGR", ypos = 2.5, 0.5, 2.6)
barplot3_f(TOTAL_WLD, "XPRP", "AGR", ypos = 160, -40, 170)
barplot4_f(TOTAL_WLD_mean, "XPRP", "AGR")
barplot5_f(scen_diff, "XPRP", "AGR")
barplot6_f(scen_diff, "XPRP", "AGR")
barplot6_f(scen_diff_upd, "XPRP", "AGR") # FIg 4 in ERL
```


# XPRP_LSP
```{r XPRP_LSP}
barplot2_f(TOTAL_WLD, "XPRP", "LSP", ypos = 2.5, 0.5, 2.6)
barplot3_f(TOTAL_WLD, "XPRP", "LSP", ypos = 160, -30, 170)
barplot4_f(TOTAL_WLD_mean, "XPRP", "LSP")
barplot5_f(scen_diff, "XPRP", "LSP")
barplot6_f(scen_diff, "XPRP", "LSP")
barplot6_f(scen_diff_upd, "XPRP", "LSP") 
```


# ECH4_AGR
NB: only CH4 emissions, NOT N2O
```{r ECH4_AGR}
barplot2_f(TOTAL_WLD, "ECH4", "AGR", ypos = 1.9, 0.5, 2)
barplot3_f(TOTAL_WLD, "ECH4", "AGR", ypos = 90, -50, 100)
barplot4_f(TOTAL_WLD_mean, "ECH4", "AGR")
barplot5_f(scen_diff, "ECH4", "AGR")
barplot6_f(scen_diff, "ECH4", "AGR") # used in ERL
barplot6_f(scen_diff_upd, "ECH4", "AGR")
```

# EN20_AGR
```{r EN20_AGR}
barplot2_f(TOTAL_WLD, "EN2O", "AGR", ypos = 1.9, 0.5, 2)
barplot3_f(TOTAL_WLD, "EN2O", "AGR", ypos = 90, -50, 100)
barplot4_f(TOTAL_WLD_mean, "EN2O", "AGR")
barplot5_f(scen_diff, "EN2O", "AGR")
barplot6_f(scen_diff, "EN2O", "AGR") # used in ERL
barplot6_f(scen_diff_upd, "EN2O", "AGR")
```

# EMIS_AGR
```{r EMIS_AGR}
barplot2_f(TOTAL_WLD, "EMIS", "AGR", ypos = 1.9, 0.5, 2)
barplot3_f(TOTAL_WLD, "EMIS", "AGR", ypos = 90, -50, 100)
barplot4_f(TOTAL_WLD_mean, "EMIS", "AGR")
barplot5_f(scen_diff, "EMIS", "AGR") 
barplot6_f(scen_diff, "EMIS", "AGR") # Fig 1 in ERL
barplot6_f(scen_diff_upd, "EMIS", "AGR")
```

# GDP
```{r fig_gdp}
fig_gdp
fig_gdp2
```

# POP
```{r fig_pop}
fig_pop
fig_pop2
```
